-- =====================================================================
-- MSC — Onda 1 / parte 4: VENDAS com itens, pagamentos e devolução
-- Finalizar venda roda numa transação só: baixa o estoque (com trava),
-- marca o IMEI como vendido, gera as contas a receber (com taxa e prazo
-- da maquininha) e dá baixa no que já entrou (dinheiro, PIX…).
-- =====================================================================

create table if not exists public.vendas (
  id                      uuid primary key default gen_random_uuid(),
  numero                  bigint generated by default as identity unique,
  cliente_id              uuid references public.clientes(id),
  data                    date not null default (now() at time zone 'America/Sao_Paulo')::date,
  status                  text not null default 'concluida'
                          check (status in ('aguardando_aprovacao','concluida','devolvida','cancelada')),
  valor_tabela_centavos   bigint not null default 0 check (valor_tabela_centavos >= 0),
  subtotal_centavos       bigint not null default 0 check (subtotal_centavos >= 0),
  desconto_centavos       bigint not null default 0 check (desconto_centavos >= 0),
  acrescimo_centavos      bigint not null default 0 check (acrescimo_centavos >= 0),
  total_centavos          bigint not null default 0 check (total_centavos >= 0),
  desconto_pct            numeric(6,2) not null default 0,
  observacao              text,
  idempotency_key         uuid unique,
  aprovado_por            uuid references public.perfis(user_id),
  aprovado_em             timestamptz,
  motivo_cancelamento     text,
  cancelada_em            timestamptz,
  cancelada_por           uuid references public.perfis(user_id),
  legado_compra_id        uuid,
  criado_por              uuid default auth.uid() references public.perfis(user_id),
  criado_em               timestamptz not null default now(),
  atualizado_em           timestamptz not null default now(),
  constraint venda_cancelamento_ok check (status <> 'cancelada' or (cancelada_em is not null and coalesce(length(trim(motivo_cancelamento)),0) > 0))
);
create index if not exists vendas_data_idx on public.vendas (data desc);
create index if not exists vendas_cliente_idx on public.vendas (cliente_id, data desc);
create index if not exists vendas_criado_por_idx on public.vendas (criado_por, criado_em desc);
create index if not exists vendas_status_idx on public.vendas (status);

create table if not exists nucleo.venda_itens (
  id                       uuid primary key default gen_random_uuid(),
  venda_id                 uuid not null references public.vendas(id),
  ordem                    smallint not null default 1,
  produto_id               uuid references nucleo.produtos(id),
  descricao                text not null,
  categoria_id             uuid references public.categorias(id),
  quantidade               numeric(15,3) not null check (quantidade > 0),
  preco_tabela_centavos    bigint not null default 0 check (preco_tabela_centavos >= 0),
  preco_unitario_centavos  bigint not null check (preco_unitario_centavos >= 0),
  desconto_centavos        bigint not null default 0 check (desconto_centavos >= 0),
  total_centavos           bigint not null check (total_centavos >= 0),
  custo_unitario_centavos  bigint not null default 0 check (custo_unitario_centavos >= 0),
  serie_id                 uuid references nucleo.produto_series(id),
  serie                    text,
  garantia_dias            int,
  devolvido_qtd            numeric(15,3) not null default 0 check (devolvido_qtd >= 0),
  check (devolvido_qtd <= quantidade)
);
create index if not exists venda_itens_venda_idx on nucleo.venda_itens (venda_id);
create index if not exists venda_itens_produto_idx on nucleo.venda_itens (produto_id);

create table if not exists public.venda_pagamentos (
  id               uuid primary key default gen_random_uuid(),
  venda_id         uuid not null references public.vendas(id),
  forma            text not null references public.formas_pagamento(forma),
  valor_centavos   bigint not null check (valor_centavos > 0),
  parcelas         smallint not null default 1 check (parcelas between 1 and 24),
  taxa_centavos    bigint not null default 0 check (taxa_centavos >= 0),
  primeiro_vencimento date
);
create index if not exists venda_pag_venda_idx on public.venda_pagamentos (venda_id);

create table if not exists public.devolucoes (
  id              uuid primary key default gen_random_uuid(),
  numero          bigint generated always as identity unique,
  venda_id        uuid not null references public.vendas(id),
  data            date not null default (now() at time zone 'America/Sao_Paulo')::date,
  motivo          text not null check (length(trim(motivo)) >= 3),
  valor_centavos  bigint not null check (valor_centavos >= 0),
  reembolso       text not null check (reembolso in ('conta','nenhum')),
  conta_id        uuid references public.contas_financeiras(id),
  criado_por      uuid default auth.uid() references public.perfis(user_id),
  criado_em       timestamptz not null default now()
);
create table if not exists nucleo.devolucao_itens (
  id              uuid primary key default gen_random_uuid(),
  devolucao_id    uuid not null references public.devolucoes(id),
  venda_item_id   uuid not null references nucleo.venda_itens(id),
  quantidade      numeric(15,3) not null check (quantidade > 0),
  valor_centavos  bigint not null check (valor_centavos >= 0)
);

alter table public.titulos drop constraint if exists titulos_venda_fk;
alter table public.titulos add constraint titulos_venda_fk foreign key (venda_id) references public.vendas(id);
alter table public.titulos drop constraint if exists titulos_devolucao_fk;
alter table public.titulos add constraint titulos_devolucao_fk foreign key (devolucao_id) references public.devolucoes(id);

alter table public.vendas            enable row level security;
alter table nucleo.venda_itens       enable row level security;
alter table public.venda_pagamentos  enable row level security;
alter table public.devolucoes        enable row level security;
alter table nucleo.devolucao_itens   enable row level security;

drop trigger if exists trg_vendas_atualizado on public.vendas;
create trigger trg_vendas_atualizado before update on public.vendas
  for each row execute function public.fn_atualizado_em();
drop trigger if exists trg_vendas_auditoria on public.vendas;
create trigger trg_vendas_auditoria after insert or update on public.vendas
  for each row execute function public.fn_auditar();
drop trigger if exists trg_devolucoes_auditoria on public.devolucoes;
create trigger trg_devolucoes_auditoria after insert on public.devolucoes
  for each row execute function public.fn_auditar();

-- ---------------------------------------------------------------------
-- Quem vê o quê
-- ---------------------------------------------------------------------
drop policy if exists vendas_ler on public.vendas;
create policy vendas_ler on public.vendas for select to authenticated using (
  (select privado.pode('vendas.ver_todas'))
  or criado_por = (select auth.uid())
  or (cliente_id is not null and (select privado.pode('clientes.ver')))
);
drop policy if exists venda_itens_ler on nucleo.venda_itens;
create policy venda_itens_ler on nucleo.venda_itens for select to authenticated using (venda_id in (select id from public.vendas));
drop policy if exists venda_pag_ler on public.venda_pagamentos;
create policy venda_pag_ler on public.venda_pagamentos for select to authenticated using (venda_id in (select id from public.vendas));
drop policy if exists devolucoes_ler on public.devolucoes;
create policy devolucoes_ler on public.devolucoes for select to authenticated using (venda_id in (select id from public.vendas));
drop policy if exists devolucao_itens_ler on nucleo.devolucao_itens;
create policy devolucao_itens_ler on nucleo.devolucao_itens for select to authenticated using (devolucao_id in (select id from public.devolucoes));
grant select on public.vendas, nucleo.venda_itens, public.venda_pagamentos, public.devolucoes, nucleo.devolucao_itens to authenticated;

create or replace view public.venda_itens with (security_invoker = true) as
select i.id, i.venda_id, i.ordem, i.produto_id, i.descricao, i.categoria_id, c.nome as categoria, i.quantidade,
       i.preco_tabela_centavos, i.preco_unitario_centavos, i.desconto_centavos, i.total_centavos,
       case when privado.pode('vendas.ver_lucro') then i.custo_unitario_centavos end as custo_unitario_centavos,
       i.serie_id, i.serie, i.garantia_dias, i.devolvido_qtd
from nucleo.venda_itens i left join public.categorias c on c.id = i.categoria_id;

create or replace view public.vendas_lista with (security_invoker = true) as
select v.*, cl.nome as cliente_nome, cl.telefone as cliente_telefone, pf.nome as vendedor_nome,
       (select string_agg(i.descricao, ', ' order by i.ordem) from nucleo.venda_itens i where i.venda_id = v.id) as itens_resumo,
       (select string_agg(distinct fp.nome, ' + ') from public.venda_pagamentos vp join public.formas_pagamento fp on fp.forma = vp.forma where vp.venda_id = v.id) as pagamentos_resumo,
       coalesce((select sum(d.valor_centavos) from public.devolucoes d where d.venda_id = v.id), 0)::bigint as devolvido_centavos,
       case when privado.pode('vendas.ver_lucro')
            then (select sum(round(i.custo_unitario_centavos * (i.quantidade - i.devolvido_qtd))) from nucleo.venda_itens i where i.venda_id = v.id)::bigint end as custo_centavos
from public.vendas v
left join public.clientes cl on cl.id = v.cliente_id
left join public.perfis pf on pf.user_id = v.criado_por;
grant select on public.venda_itens, public.vendas_lista to authenticated;

-- ---------------------------------------------------------------------
-- Efetivar: estoque + financeiro (chamado por finalizar/aprovar)
-- ---------------------------------------------------------------------
create or replace function privado.efetivar_venda(p_venda uuid)
returns void language plpgsql security definer set search_path = nucleo, public as $$
declare v record; i record; s record; pg record; f record; v_hoje date := (now() at time zone 'America/Sao_Paulo')::date;
        v_n int; v_k int; v_parte bigint; v_taxa_parte bigint; v_soma bigint; v_soma_taxa bigint; v_venc date; v_tid uuid;
        v_desc text; v_cli text;
begin
  select * into v from public.vendas where id = p_venda for update;
  select nome into v_cli from public.clientes where id = v.cliente_id;

  for i in select vi.*, pr.controla_estoque, pr.controla_serie from nucleo.venda_itens vi
           left join nucleo.produtos pr on pr.id = vi.produto_id where vi.venda_id = p_venda order by vi.ordem loop
    if i.produto_id is null or not i.controla_estoque then continue; end if;
    if i.serie_id is not null then
      select * into s from nucleo.produto_series where id = i.serie_id for update;
      if not (s.status = 'disponivel' or (s.status = 'reservado' and s.venda_item_id = i.id)) then
        raise exception 'O IMEI/série % não está disponível (situação: %).', s.serie, s.status;
      end if;
      update nucleo.produto_series set status = 'vendido', venda_item_id = i.id where id = s.id;
      insert into nucleo.estoque_movimentos (produto_id, tipo, quantidade, custo_unitario_centavos, serie_id, venda_id, venda_item_id, motivo, criado_por)
      values (i.produto_id, 'venda', -1, s.custo_centavos, s.id, p_venda, i.id, 'Venda nº ' || v.numero, v.criado_por);
    else
      insert into nucleo.estoque_movimentos (produto_id, tipo, quantidade, custo_unitario_centavos, venda_id, venda_item_id, motivo, criado_por)
      values (i.produto_id, 'venda', -i.quantidade, i.custo_unitario_centavos, p_venda, i.id, 'Venda nº ' || v.numero, v.criado_por);
    end if;
  end loop;

  v_desc := 'Venda nº ' || v.numero || coalesce(' — ' || v_cli, '');
  for pg in select * from public.venda_pagamentos where venda_id = p_venda loop
    select * into f from public.formas_pagamento where forma = pg.forma;
    if pg.forma = 'credito' and f.antecipar then v_n := 1; else v_n := pg.parcelas; end if;
    if pg.forma not in ('credito','crediario','boleto') then v_n := 1; end if;
    v_soma := 0; v_soma_taxa := 0;
    for v_k in 1..v_n loop
      if v_k = v_n then v_parte := pg.valor_centavos - v_soma; v_taxa_parte := pg.taxa_centavos - v_soma_taxa;
      else v_parte := pg.valor_centavos / v_n; v_taxa_parte := pg.taxa_centavos / v_n; end if;
      v_soma := v_soma + v_parte; v_soma_taxa := v_soma_taxa + v_taxa_parte;
      v_venc := coalesce(pg.primeiro_vencimento, v.data + f.dias_repasse);
      if v_k > 1 then v_venc := (v_venc + make_interval(months => v_k - 1))::date; end if;
      insert into public.titulos (tipo, descricao, categoria_id, cliente_id, venda_id, forma_pagamento, conta_prevista_id,
                                  competencia, vencimento, parcela, parcelas, valor_centavos, taxa_prevista_centavos, baixa_automatica, criado_por)
      values ('receber', v_desc, privado.cat('vendas'), v.cliente_id, p_venda, pg.forma, f.conta_id,
              v.data, v_venc, v_k, v_n, v_parte, v_taxa_parte, f.baixa_automatica and f.conta_id is not null, v.criado_por)
      returning id into v_tid;
      if f.baixa_automatica and f.conta_id is not null and v_venc <= v_hoje then
        perform privado.baixar(v_tid, v_venc, f.conta_id, v_parte, 0, 0, 0, v_taxa_parte, true);
      end if;
    end loop;
  end loop;

  update public.vendas set status = 'concluida' where id = p_venda;
end $$;

-- ---------------------------------------------------------------------
-- FINALIZAR VENDA
-- p: {chave (uuid p/ não duplicar), cliente_id, observacao, desconto_centavos, acrescimo_centavos,
--     itens:[{produto_id | (descricao, categoria_id), quantidade, preco_unitario_centavos, desconto_centavos, serie_id, garantia_dias}],
--     pagamentos:[{forma, valor_centavos, parcelas, primeiro_vencimento}]}
-- ---------------------------------------------------------------------
create or replace function public.finalizar_venda(p jsonb)
returns jsonb language plpgsql security definer set search_path = nucleo, public as $$
declare v_key uuid := nullif(p->>'chave','')::uuid; v_exist record; v_id uuid; v_num bigint; it jsonb; pg jsonb; pr record; s record;
        v_ordem int := 0; v_qtd numeric; v_preco bigint; v_tab bigint; v_desc_item bigint; v_total_item bigint; v_custo bigint;
        v_descricao text; v_cat uuid; v_gar int; v_tabela bigint := 0; v_sub bigint := 0; v_desc bigint; v_acr bigint; v_total bigint;
        v_pct numeric := 0; v_pagto bigint := 0; v_cli uuid := nullif(p->>'cliente_id','')::uuid; v_emp record; v_forma record;
        v_item_id uuid; v_status text; v_parc int; v_series uuid[] := '{}'; v_sid uuid; v_stxt text;
begin
  if not privado.pode('vendas.criar') then raise exception 'Sem permissão para vender.'; end if;
  if v_key is not null then
    select id, numero, status into v_exist from public.vendas where idempotency_key = v_key;
    if found then return jsonb_build_object('id', v_exist.id, 'numero', v_exist.numero, 'status', v_exist.status, 'repetida', true); end if;
  end if;
  if jsonb_array_length(coalesce(p->'itens','[]'::jsonb)) = 0 then raise exception 'Adicione pelo menos um item.'; end if;
  if v_cli is not null and not exists (select 1 from public.clientes where id = v_cli and ativo) then raise exception 'Cliente não encontrado ou inativo.'; end if;
  select * into v_emp from public.empresa where id = 1;

  insert into public.vendas (cliente_id, observacao, idempotency_key, status)
  values (v_cli, nullif(trim(p->>'observacao'),''), v_key, 'aguardando_aprovacao')
  returning id, numero into v_id, v_num;

  for it in select * from jsonb_array_elements(p->'itens') loop
    v_ordem := v_ordem + 1;
    v_qtd := coalesce((it->>'quantidade')::numeric, 1);
    v_preco := (it->>'preco_unitario_centavos')::bigint;
    v_desc_item := coalesce((it->>'desconto_centavos')::bigint, 0);
    if v_qtd <= 0 then raise exception 'Quantidade inválida no item %.', v_ordem; end if;
    if v_preco is null or v_preco < 0 then raise exception 'Preço inválido no item %.', v_ordem; end if;
    v_sid := null; v_stxt := null;
    if nullif(it->>'produto_id','') is not null then
      select * into pr from nucleo.produtos where id = (it->>'produto_id')::uuid;
      if not found or not pr.ativo then raise exception 'Produto do item % não encontrado ou inativo.', v_ordem; end if;
      v_tab := pr.preco_venda_centavos;
      v_descricao := pr.nome || case when pr.condicao <> 'novo' then ' (' || pr.condicao || ')' else '' end;
      v_cat := pr.categoria_id;
      v_custo := pr.custo_medio_centavos;
      v_gar := coalesce(nullif(it->>'garantia_dias','')::int, pr.garantia_dias, v_emp.garantia_padrao_dias);
      if pr.controla_serie then
        if nullif(it->>'serie_id','') is null then raise exception 'Escolha o IMEI/série de "%".', pr.nome; end if;
        if v_qtd <> 1 then raise exception 'Produto com IMEI vai 1 por linha ("%").', pr.nome; end if;
        select * into s from nucleo.produto_series where id = (it->>'serie_id')::uuid for update;
        if not found or s.produto_id <> pr.id then raise exception 'IMEI/série não pertence a "%".', pr.nome; end if;
        if s.status <> 'disponivel' then raise exception 'O IMEI/série % não está disponível.', s.serie; end if;
        if s.id = any(v_series) then raise exception 'O IMEI/série % está repetido na venda.', s.serie; end if;
        v_series := v_series || s.id;
        v_custo := s.custo_centavos;
        v_sid := s.id; v_stxt := s.serie;
      end if;
    else
      v_descricao := nullif(trim(it->>'descricao'),'');
      v_cat := nullif(it->>'categoria_id','')::uuid;
      if v_descricao is null then raise exception 'Descreva o item %.', v_ordem; end if;
      if v_cat is null or (select tipo from public.categorias where id = v_cat) <> 'venda' then raise exception 'Escolha a categoria do item %.', v_ordem; end if;
      v_tab := v_preco;
      v_custo := case when privado.pode('estoque.ver_custo') then coalesce((it->>'custo_unitario_centavos')::bigint, 0) else 0 end;
      v_gar := nullif(it->>'garantia_dias','')::int;
    end if;
    v_total_item := round(v_qtd * v_preco)::bigint - v_desc_item;
    if v_desc_item < 0 or v_total_item < 0 then raise exception 'Desconto maior que o valor no item %.', v_ordem; end if;
    insert into nucleo.venda_itens (venda_id, ordem, produto_id, descricao, categoria_id, quantidade, preco_tabela_centavos, preco_unitario_centavos,
                                    desconto_centavos, total_centavos, custo_unitario_centavos, serie_id, serie, garantia_dias)
    values (v_id, v_ordem, nullif(it->>'produto_id','')::uuid, v_descricao, v_cat, v_qtd, v_tab, v_preco,
            v_desc_item, v_total_item, v_custo, v_sid, v_stxt, v_gar)
    returning id into v_item_id;
    if v_sid is not null then
      update nucleo.produto_series set status = 'reservado', venda_item_id = v_item_id where id = v_sid;
    end if;
    v_tabela := v_tabela + round(v_qtd * v_tab)::bigint;
    v_sub := v_sub + v_total_item;
  end loop;

  v_desc := coalesce((p->>'desconto_centavos')::bigint, 0);
  v_acr := coalesce((p->>'acrescimo_centavos')::bigint, 0);
  if v_desc < 0 or v_desc > v_sub then raise exception 'Desconto inválido.'; end if;
  if v_acr < 0 then raise exception 'Acréscimo inválido.'; end if;
  v_total := v_sub - v_desc + v_acr;
  if v_tabela > 0 then v_pct := round(greatest(0, v_tabela - (v_sub - v_desc))::numeric * 100 / v_tabela, 2); end if;

  if v_total > 0 and jsonb_array_length(coalesce(p->'pagamentos','[]'::jsonb)) = 0 then raise exception 'Informe a forma de pagamento.'; end if;
  for pg in select * from jsonb_array_elements(coalesce(p->'pagamentos','[]'::jsonb)) loop
    select * into v_forma from public.formas_pagamento where forma = pg->>'forma' and ativo;
    if not found then raise exception 'Forma de pagamento inválida: %.', pg->>'forma'; end if;
    v_parc := coalesce((pg->>'parcelas')::int, 1);
    if v_parc < 1 or v_parc > 24 then raise exception 'Número de parcelas inválido.'; end if;
    if v_parc > 1 and v_forma.forma not in ('credito','crediario','boleto') then raise exception 'Parcelas só no crédito, crediário ou boleto.'; end if;
    if v_forma.forma = 'crediario' and v_cli is null then raise exception 'Venda no crediário/fiado precisa de cliente cadastrado.'; end if;
    if coalesce((pg->>'valor_centavos')::bigint, 0) <= 0 then raise exception 'Valor de pagamento inválido.'; end if;
    v_pagto := v_pagto + (pg->>'valor_centavos')::bigint;
    insert into public.venda_pagamentos (venda_id, forma, valor_centavos, parcelas, taxa_centavos, primeiro_vencimento)
    values (v_id, v_forma.forma, (pg->>'valor_centavos')::bigint, v_parc,
            round((pg->>'valor_centavos')::bigint * privado.taxa_forma(v_forma.forma, v_parc) / 100)::bigint,
            nullif(pg->>'primeiro_vencimento','')::date);
  end loop;
  if v_pagto <> v_total then
    raise exception 'Os pagamentos somam R$ % mas o total é R$ %.', to_char(v_pagto/100.0,'FM999G999G990D00'), to_char(v_total/100.0,'FM999G999G990D00');
  end if;

  update public.vendas set valor_tabela_centavos = v_tabela, subtotal_centavos = v_sub, desconto_centavos = v_desc,
         acrescimo_centavos = v_acr, total_centavos = v_total, desconto_pct = v_pct
  where id = v_id;

  if v_pct > v_emp.desconto_max_pct and not privado.pode('vendas.desconto_livre') then
    v_status := 'aguardando_aprovacao';
  else
    if v_pct > v_emp.desconto_max_pct then update public.vendas set aprovado_por = auth.uid(), aprovado_em = now() where id = v_id; end if;
    perform privado.efetivar_venda(v_id);
    v_status := 'concluida';
  end if;
  return jsonb_build_object('id', v_id, 'numero', v_num, 'status', v_status, 'total_centavos', v_total, 'desconto_pct', v_pct);
end $$;

-- ---------------------------------------------------------------------
-- APROVAR / REPROVAR (desconto acima do limite)
-- ---------------------------------------------------------------------
create or replace function public.aprovar_venda(p_venda uuid, p_aprovar boolean, p_motivo text default null)
returns void language plpgsql security definer set search_path = nucleo, public as $$
declare v record;
begin
  if not privado.pode('vendas.aprovar') then raise exception 'Sem permissão para aprovar vendas.'; end if;
  select * into v from public.vendas where id = p_venda for update;
  if v.status <> 'aguardando_aprovacao' then raise exception 'Esta venda não está aguardando aprovação.'; end if;
  if p_aprovar then
    update public.vendas set aprovado_por = auth.uid(), aprovado_em = now() where id = p_venda;
    perform privado.efetivar_venda(p_venda);
  else
    update nucleo.produto_series set status = 'disponivel', venda_item_id = null
    where venda_item_id in (select id from nucleo.venda_itens where venda_id = p_venda) and status = 'reservado';
    update public.vendas set status = 'cancelada', cancelada_em = now(), cancelada_por = auth.uid(),
           motivo_cancelamento = 'Reprovada: ' || coalesce(nullif(trim(p_motivo),''), 'desconto não aprovado')
    where id = p_venda;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- CANCELAR VENDA (estorna estoque e financeiro)
-- ---------------------------------------------------------------------
create or replace function public.cancelar_venda(p_venda uuid, p_motivo text)
returns void language plpgsql security definer set search_path = nucleo, public as $$
declare v record; i record; t record; v_hoje date := (now() at time zone 'America/Sao_Paulo')::date;
begin
  if coalesce(length(trim(p_motivo)),0) < 3 then raise exception 'Informe o motivo do cancelamento.'; end if;
  select * into v from public.vendas where id = p_venda for update;
  if not found then raise exception 'Venda não encontrada.'; end if;
  if v.status in ('cancelada','devolvida') then raise exception 'Esta venda já está %.', v.status; end if;
  if not (privado.pode('vendas.cancelar_todas')
          or (privado.pode('vendas.cancelar_proprias') and v.criado_por = auth.uid()
              and (v.criado_em at time zone 'America/Sao_Paulo')::date = v_hoje)) then
    raise exception 'Sem permissão para cancelar esta venda.';
  end if;
  if exists (select 1 from public.devolucoes where venda_id = p_venda) then
    raise exception 'Esta venda já teve devolução. Use a devolução para os itens que faltam.';
  end if;

  if v.status = 'aguardando_aprovacao' then
    update nucleo.produto_series set status = 'disponivel', venda_item_id = null
    where venda_item_id in (select id from nucleo.venda_itens where venda_id = p_venda) and status = 'reservado';
  else
    for i in select vi.*, pr.controla_estoque from nucleo.venda_itens vi join nucleo.produtos pr on pr.id = vi.produto_id
             where vi.venda_id = p_venda and pr.controla_estoque loop
      if i.serie_id is not null then
        update nucleo.produto_series set status = 'disponivel', venda_item_id = null where id = i.serie_id;
        insert into nucleo.estoque_movimentos (produto_id, tipo, quantidade, custo_unitario_centavos, serie_id, venda_id, venda_item_id, motivo)
        values (i.produto_id, 'cancelamento_venda', 1, i.custo_unitario_centavos, i.serie_id, p_venda, i.id, 'Cancelamento da venda nº ' || v.numero);
      else
        insert into nucleo.estoque_movimentos (produto_id, tipo, quantidade, custo_unitario_centavos, venda_id, venda_item_id, motivo)
        values (i.produto_id, 'cancelamento_venda', i.quantidade, i.custo_unitario_centavos, p_venda, i.id, 'Cancelamento da venda nº ' || v.numero);
      end if;
    end loop;
    for t in select id from public.titulos where venda_id = p_venda and status <> 'cancelado' loop
      perform privado.cancelar_titulo(t.id, 'Venda cancelada: ' || trim(p_motivo), true);
    end loop;
  end if;
  update public.vendas set status = 'cancelada', motivo_cancelamento = trim(p_motivo), cancelada_em = now(), cancelada_por = auth.uid()
  where id = p_venda;
end $$;

-- ---------------------------------------------------------------------
-- DEVOLUÇÃO / TROCA (parcial ou total)
-- p: {venda_id, motivo, itens:[{venda_item_id, quantidade}], reembolso:'conta'|'nenhum', conta_id}
-- ---------------------------------------------------------------------
create or replace function public.devolver_venda(p jsonb)
returns uuid language plpgsql security definer set search_path = nucleo, public as $$
declare v record; it jsonb; i record; v_dev uuid; v_qtd numeric; v_valor bigint; v_total bigint := 0; v_tid uuid; v_hoje date := (now() at time zone 'America/Sao_Paulo')::date;
        v_reemb text := coalesce(p->>'reembolso','conta');
begin
  if not privado.pode('vendas.devolver') then raise exception 'Sem permissão para devolução.'; end if;
  if coalesce(length(trim(p->>'motivo')),0) < 3 then raise exception 'Informe o motivo da devolução.'; end if;
  select * into v from public.vendas where id = (p->>'venda_id')::uuid for update;
  if v.status <> 'concluida' then raise exception 'Só dá para devolver venda concluída.'; end if;
  if v_reemb = 'conta' and nullif(p->>'conta_id','') is null then raise exception 'Escolha de qual conta sai o dinheiro devolvido.'; end if;

  insert into public.devolucoes (venda_id, motivo, valor_centavos, reembolso, conta_id)
  values (v.id, trim(p->>'motivo'), 0, v_reemb, nullif(p->>'conta_id','')::uuid) returning id into v_dev;

  for it in select * from jsonb_array_elements(p->'itens') loop
    v_qtd := (it->>'quantidade')::numeric;
    if coalesce(v_qtd,0) <= 0 then continue; end if;
    select vi.*, pr.controla_estoque into i from nucleo.venda_itens vi left join nucleo.produtos pr on pr.id = vi.produto_id
      where vi.id = (it->>'venda_item_id')::uuid and vi.venda_id = v.id for update of vi;
    if not found then raise exception 'Item não pertence a esta venda.'; end if;
    if v_qtd > i.quantidade - i.devolvido_qtd then raise exception 'Quantidade maior do que a vendida em "%".', i.descricao; end if;
    -- valor proporcional, já com o desconto/acréscimo geral da venda
    v_valor := round(i.total_centavos::numeric * v_qtd / i.quantidade
                     * case when v.subtotal_centavos > 0 then v.total_centavos::numeric / v.subtotal_centavos else 1 end)::bigint;
    v_total := v_total + v_valor;
    insert into nucleo.devolucao_itens (devolucao_id, venda_item_id, quantidade, valor_centavos) values (v_dev, i.id, v_qtd, v_valor);
    update nucleo.venda_itens set devolvido_qtd = devolvido_qtd + v_qtd where id = i.id;
    if i.produto_id is not null and i.controla_estoque then
      if i.serie_id is not null then
        update nucleo.produto_series set status = 'disponivel', venda_item_id = null where id = i.serie_id;
      end if;
      insert into nucleo.estoque_movimentos (produto_id, tipo, quantidade, custo_unitario_centavos, serie_id, venda_id, venda_item_id, devolucao_id, motivo)
      values (i.produto_id, 'devolucao_cliente', v_qtd, i.custo_unitario_centavos, i.serie_id, v.id, i.id, v_dev, 'Devolução da venda nº ' || v.numero);
    end if;
  end loop;
  if v_total = 0 and not exists (select 1 from nucleo.devolucao_itens where devolucao_id = v_dev) then raise exception 'Escolha os itens devolvidos.'; end if;
  update public.devolucoes set valor_centavos = v_total where id = v_dev;

  if v_reemb = 'conta' and v_total > 0 then
    insert into public.titulos (tipo, descricao, categoria_id, cliente_id, devolucao_id, competencia, vencimento, valor_centavos)
    values ('pagar', 'Devolução da venda nº ' || v.numero, privado.cat('devolucao'), v.cliente_id, v_dev, v_hoje, v_hoje, v_total)
    returning id into v_tid;
    perform privado.baixar(v_tid, v_hoje, (p->>'conta_id')::uuid, v_total);
  end if;

  if not exists (select 1 from nucleo.venda_itens where venda_id = v.id and devolvido_qtd < quantidade) then
    update public.vendas set status = 'devolvida' where id = v.id;
  end if;
  return v_dev;
end $$;

-- Ligar um cliente a uma venda balcão depois
create or replace function public.vincular_cliente_venda(p_venda uuid, p_cliente uuid)
returns void language plpgsql security definer set search_path = public as $$
declare v record;
begin
  select * into v from public.vendas where id = p_venda for update;
  if not (privado.pode('vendas.ver_todas') or (privado.pode('vendas.criar') and v.criado_por = auth.uid())) then
    raise exception 'Sem permissão.';
  end if;
  if v.cliente_id is not null then raise exception 'Esta venda já tem cliente.'; end if;
  update public.vendas set cliente_id = p_cliente where id = p_venda;
  update public.titulos set cliente_id = p_cliente where venda_id = p_venda;
end $$;
